service: ravepads

provider:
  name: aws
  runtime: java11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logs:
    restApi: true
    role: arn:aws:iam::621709793940:role/rave-api-gteway-role
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - 'multipart/form-data'
    apiKeys:
      - basic:
          - basicPlanKey
    usagePlan:
      - basic:
          quota:
            limit: 100
            period: MONTH
          throttle:
            rateLimit: 5
            burstLimit: 20
package:
  artifact: target/ravepads-0.1.jar

custom:
  env:
    dev:
      roleEnv: 'dev'
      memorySize: 128
      lambda_role: arn:aws:iam::621709793940:role/ravepads-lambda
      #authorizer_arn: arn:aws:lambda:us-west-2:659764204348:function:bfc-authorizer-dev
      environment:
        LOG_LEVEL: INFO

functions:
  greeter:
    handler: com.rave.pads.Application
    role: ${self:custom.env.${self:provider.stage}.lambda_role}
    events:
      - http:
          path: hud/properties/{stateCode}
          method: GET
          cors: true
          operationId: hudDownload
          private: true
      - http:
          path: ai-trainor
          method: GET
          cors: true
          operationId: aiTrainorHome
      - http:
          path: ai-trainor/request-upload/{contentType}/{fileName}
          method: GET
          cors:
            headers: '*'
          request:
            parameters:
              paths:
                contentType: true
                fileName: true
          operationId: requestUpload
          private: true

